[project]
name = "marvel-dialogue-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "locket-hub", email = "84401976+locket-hub@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
marvel-dialogue-finder = "marvel_dialogue_finder:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
